package com.labs1904.tracker.utils

val STATE_NAME_MAP = mapOf(
            "AL" to "Alabama",
            "AK" to "Alaska",
            "AB" to "Alberta",
            "AZ" to "Arizona",
            "AR" to "Arkansas",
            "BC" to "British Columbia",
            "CA" to "California",
            "CO" to "Colorado",
            "CT" to "Connecticut",
            "DE" to "Delaware",
            "DC" to "District Of Columbia",
            "FL" to "Florida",
            "GA" to "Georgia",
            "GU" to "Guam",
            "HI" to "Hawaii",
            "ID" to "Idaho",
            "IL" to "Illinois",
            "IN" to "Indiana",
            "IA" to "Iowa",
            "KS" to "Kansas",
            "KY" to "Kentucky",
            "LA" to "Louisiana",
            "ME" to "Maine",
            "MB" to "Manitoba",
            "MD" to "Maryland",
            "MA" to "Massachusetts",
            "MI" to "Michigan",
            "MN" to "Minnesota",
            "MS" to "Mississippi",
            "MO" to "Missouri",
            "MT" to "Montana",
            "NE" to "Nebraska",
            "NV" to "Nevada",
            "NB" to "New Brunswick",
            "NH" to "New Hampshire",
            "NJ" to "New Jersey",
            "NM" to "New Mexico",
            "NY" to "New York",
            "NF" to "Newfoundland",
            "NC" to "North Carolina",
            "ND" to "North Dakota",
            "NT" to "Northwest Territories",
            "NS" to "Nova Scotia",
            "NU" to "Nunavut",
            "OH" to "Ohio",
            "OK" to "Oklahoma",
            "ON" to "Ontario",
            "OR" to "Oregon",
            "PA" to "Pennsylvania",
            "PE" to "Prince Edward Island",
            "PR" to "Puerto Rico",
            "QC" to "Quebec",
            "RI" to "Rhode Island",
            "SK" to "Saskatchewan",
            "SC" to "South Carolina",
            "SD" to "South Dakota",
            "TN" to "Tennessee",
            "TX" to "Texas",
            "UT" to "Utah",
            "VT" to "Vermont",
            "VI" to "Virgin Islands",
            "VA" to "Virginia",
            "WA" to "Washington",
            "WV" to "West Virginia",
            "WI" to "Wisconsin",
            "WY" to "Wyoming",
            "YT" to "Yukon Territory"
)